name: EstudiosUrbanos
favicon: null
layout_spectrum: 0.3108832386787981
typography_spectrum: 0.8848192514851689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.24541158508509398
  lightness: 0.5707377993967384
  saturation: 0.916987722273916
  rhythmicContrast: 0.0785391335375607
purpose: []
